project2/Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace project2.Controllers
{
    public class ChangePasswordController : Controller
    {
        socialnetworkEntities5 db = new socialnetworkEntities5();
        // GET: ChangePassword
        public ActionResult Index()
        {
            if (Session["userid"] == null)
            {

                return RedirectToAction("Index", "Login");
            }
            int uid = Int32.Parse(Session["userid"].ToString());
            var userdata = (from u in db.users where u.id == uid select u).FirstOrDefault();
            ViewBag.edituserdata = userdata;

            return View(userdata);
        }


        public ActionResult changepass(user rgs)
        {
            user useds = new user();


            var usname = (from p in db.users where p.user_password == rgs.CompairPassword select p).FirstOrDefault();
            if (usname != null)
            {
                if (rgs.NewPassword == rgs.ConfirmNewPassword)
                {
                    int uid = Int32.Parse(Session["userid"].ToString());
                    user us = (from e in db.users where e.id == uid select e).FirstOrDefault(); ;
                    us.id = Int32.Parse(Session["userid"].ToString());

                    us.user_password = rgs.NewPassword;

                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                else
                {
                    ViewBag.compMessage = "password or Conformpassword are mismatch";
                    return View("Index");
                }
            }
            else
            {
                ViewBag.cpMessage = "not match your current password";
                return View("Index");

            }
             return View("Index");
        }




    }


}

project2/Controllers/HobbiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using project2.Models;

namespace project2.Controllers
{
    public class HobbiesController : Controller
    {
        socialnetworkEntities5 db = new socialnetworkEntities5();
        // GET: Hobbies
        public ActionResult Index()
        {
            if (Session["userid"] == null)
            {

                return RedirectToAction("Index", "Login");
            }
            int uid = Int32.Parse(Session["userid"].ToString());
            var Hobbiesdata = (from h in db.hobbies where h.id == uid select h).FirstOrDefault();
            ViewBag.edithobbiesdata = Hobbiesdata;
       
            return View(Hobbiesdata);
        

        }

        // GET: Hobbies/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Hobbies/Create

        // POST: Hobbies/Create
        [HttpPost]
        public ActionResult Create(hobbies hs)
        {
            try
            {


                hobby hss = new hobby();
                hss.user_id = Int32.Parse(Session["userid"].ToString());
                hss.hobbies = hs.Hobbies;
                hss.favorite_tv_shows = hs.favorite_tv_shows;
                hss.favorite_movies = hs.favorite_movies;
                hss.favorite_games = hs.favorite_games;
                hss.favorite_books = hs.favorite_books;
                hss.favorite_writers = hs.favorite_writers;
                hss.other_interest = hs.other_interest;

                hss.create_date = DateTime.Now;

                db.hobbies.Add(hss);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Hobbies/Create
        [HttpPost]
        public ActionResult Edit(hobbies hs)
        {
            try
            {


                int uid = Int32.Parse(Session["userid"].ToString());
                hobby hb = (from e in db.hobbies where e.id == uid select e).FirstOrDefault();
                hb.user_id = Int32.Parse(Session["userid"].ToString());
                hb.hobbies = hs.Hobbies;
                hb.favorite_tv_shows = hs.favorite_tv_shows;
                hb.favorite_movies = hs.favorite_movies;
                hb.favorite_games = hs.favorite_games;
                hb.favorite_books = hs.favorite_books;
                hb.favorite_writers = hs.favorite_writers;
                hb.other_interest = hs.other_interest;

           
                db.SaveChanges();
                return RedirectToAction("Index");

             }
            catch
            {
                return RedirectToAction("Index");
            }
        }

    }

}

project2/Controllers/PersonalInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace project2.Controllers
{
    public class PersonalInfoController : Controller
    {
        socialnetworkEntities5 db = new socialnetworkEntities5();

        // GET: PersonalInfo
        public ActionResult Index()
        {
            if (Session["userid"] == null)
            {

                return RedirectToAction("Index", "Login");
            }
            int uid = Int32.Parse(Session["userid"].ToString());
            var userdata = (from u in db.users where u.id == uid select u).FirstOrDefault();
            ViewBag.edituserdata = userdata;


            return View(userdata);
        }

        // GET: PersonalInfo/Details/5
        public ActionResult Details(int id)
        {

            return View();
        }

        // GET: PersonalInfo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PersonalInfo/Create
        [HttpPost]
        public ActionResult Create(user uses)
        {
            try
            {

                int uid = Int32.Parse(Session["userid"].ToString());
                user us = (from u in db.users where u.id == uid select u).FirstOrDefault();
                us.user_name = uses.user_name;
                us.user_bio = uses.user_bio;
                us.user_dateofbirth = uses.user_dateofbirth;
                us.user_occupation = uses.user_occupation;
                us.user_status = uses.user_status;
                us.user_name_id = uses.user_name_id;
                us.user_email = uses.user_email;
                us.user_contect = uses.user_contect;
                us.user_birthplace = uses.user_birthplace;
                us.user_livesin = uses.user_livesin;
                us.user_website = uses.user_website;

                
                //db.users.Add(us);
                db.SaveChanges();
                // TODO: Add insert logic here

                return RedirectToAction("Index");

            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: PersonalInfo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PersonalInfo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {

                // TODO: Add update logic here


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PersonalInfo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PersonalInfo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

project2/Views/Shared/_DashbordLayoutPage.cshtml
@{
    Layout = "~/Views/Shared/_MenuLayoutPage.cshtml";
}




<!-- Main Header Account -->

<div class="main-header">
    <div class="content-bg-wrap bg-account"></div>
    <div class="container">
        <div class="row">
            <div class="col col-lg-8 m-auto col-md-8 col-sm-12 col-12">
                <div class="main-header-content">
                    <h1>Your Account Dashboard</h1>
                    <p>
                        Welcome to your account dashboard! Here you’ll find everything you need to change your profile
                        information, settings, read notifications and requests, view your latest messages, change your pasword and much
                        more! Also you can create or manage your own favourite page, have fun!
                    </p>
                </div>
            </div>
        </div>
    </div>
    <img class="img-bottom" src="~/Content/img/account-bottom.png" alt="friends">
</div>

<!-- ... end Main Header Account -->
<!-- Your Account Personal Information -->
<div class="container">
    <div class="row">
        @RenderBody()

        <div class="col col-xl-3 order-xl-1 col-lg-3 order-lg-1 col-md-12 order-md-2 col-sm-12  responsive-display-none">
            <div class="ui-block">



                <!-- Your Profile  -->

                <div class="your-profile">
                    <div class="ui-block-title ui-block-title-small">
                        <h6 class="title">Your PROFILE</h6>
                    </div>

                    <div id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <h6 class="mb-0">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Profile Settings
                                        <svg class="olymp-dropdown-arrow-icon"><use xlink:href="~/Content/svg-icons/sprites/icons.svg#olymp-dropdown-arrow-icon"></use></svg>
                                    </a>
                                </h6>
                            </div>

                            <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                                <ul class="your-profile-menu">
                                    <li>
                                        @Html.ActionLink("Personal Information", "Index", "PersonalInfo")

                                   </li>
                                
                                    <li>
                                        @Html.ActionLink("Change Password", "Index", "ChangePassword")

                                     </li>
                                    <li>
                                        @Html.ActionLink("Hobbies and Interests", "Index", "Hobbies")
                                     </li>
                                    <li>
                                        @Html.ActionLink("Education", "Index", "Education")

                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    @*<div class="ui-block-title">
                       <ul>
                           <li>
                               <b>
                                   @Html.ActionLink("Notification", "Index", "Notification")
                               </b>
                        </li>
                        </ul>
                    </div>
                    <div class="ui-block-title">
                        <ul>
                            <li>
                                <b>
                                    @Html.ActionLink("FriendRequest", "Index", "FriendRequest")
                                </b>
                            </li>
                        </ul>
                    </div>*@
                 </div>

                <!-- ... end Your Profile  -->


            </div>
        </div>
    </div>
</div>

<!-- ... end Your Account Personal Information -->

project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<!-- Mirrored from html.crumina.net/html-olympus/01-LandingPage.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 23 Jan 2019 19:40:31 GMT -->
<head>

	<title>Landing Page</title>

	<!-- Required meta tags always come first -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<!-- Main Font -->
	<script src="~/Scripts/js/webfontloader.min.js"></script>

	<script>
		WebFont.load({
			google: {
				families: ['Roboto:300,400,500,700:latin']
			}
		});
	</script>

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="~/Content/Bootstrap/dist/css/bootstrap-reboot.css">
	<link rel="stylesheet" type="text/css" href="~/Content/Bootstrap/dist/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="~/Content/Bootstrap/dist/css/bootstrap-grid.css">

	<!-- Main Styles CSS -->
	<link rel="stylesheet" type="text/css" href="~/Content/css/main.min.css">
	<link rel="stylesheet" type="text/css" href="~/Content/css/fonts.min.css">



</head>

<body class="landing-page">

	<div class="content-bg-wrap"></div>


	<!-- Header Standard Landing  -->

	<div class="header--standard header--standard-landing" id="header--standard">
		<div class="container">
			<div class="header--standard-wrap">

				<a href="#" class="logo">
					<div class="img-wrap">
						<img src="~/Content/img/logo.png" alt="Olympus">
						<img src="~/Content/img/logo-colored-small.png" alt="Olympus" class="logo-colored">
					</div>
					<div class="title-block">
						<h6 class="logo-title">Social Gram</h6>
						<div class="sub-title">SOCIAL NETWORK</div>
					</div>
				</a>

				<a href="#" class="open-responsive-menu js-open-responsive-menu">
					<svg class="olymp-menu-icon"><use xlink:href="~/Content/svg-icons/sprites/icons.svg#olymp-menu-icon"></use></svg>
				</a>

			</div>
		</div>
	</div>

	<!-- ... end Header Standard Landing  -->
	<div class="header-spacer--standard"></div>

	<div class="container">
		<div class="row display-flex">
			<div class="col col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
				<div class="landing-content">
					<h1>Welcome to the Best Social Network in the World</h1>

					<a data-toggle="tab" href="#home" role="tab" class="btn btn-md btn-border c-white">Register Now!</a>
				</div>
			</div>

			<div class="col col-xl-5 col-lg-6 col-md-12 col-sm-12 col-12">

				<!-- Login-Registration Form  -->

				@RenderBody()


				<!-- ... end Login-Registration Form  -->
			</div>
		</div>
	</div>

	<script src="~/Vender/dashbord.js"></script>


	<!-- JS Scripts -->
	<script src="~/Scripts/js/jquery-3.2.1.js"></script>
	<script src="~/Scripts/js/jquery.appear.js"></script>
	<script src="~/Scripts/js/jquery.mousewheel.js"></script>
	<script src="~/Scripts/js/perfect-scrollbar.js"></script>
	<script src="~/Scripts/js/jquery.matchHeight.js"></script>
	<script src="~/Scripts/js/svgxuse.js"></script>
	<script src="~/Scripts/js/imagesloaded.pkgd.js"></script>
	<script src="~/Scripts/js/Headroom.js"></script>
	<script src="~/Scripts/js/velocity.js"></script>
	<script src="~/Scripts/js/ScrollMagic.js"></script>
	<script src="~/Scripts/js/jquery.waypoints.js"></script>
	<script src="~/Scripts/js/jquery.countTo.js"></script>
	<script src="~/Scripts/js/popper.min.js"></script>
	<script src="~/Scripts/js/material.min.js"></script>
	<script src="~/Scripts/js/bootstrap-select.js"></script>
	<script src="~/Scripts/js/smooth-scroll.js"></script>
	<script src="~/Scripts/js/selectize.js"></script>
	<script src="~/Scripts/js/swiper.jquery.js"></script>
	<script src="~/Scripts/js/moment.js"></script>
	<script src="~/Scripts/js/daterangepicker.js"></script>
	<script src="~/Scripts/js/simplecalendar.js"></script>
	<script src="~/Scripts/js/fullcalendar.js"></script>
	<script src="~/Scripts/js/isotope.pkgd.js"></script>
	<script src="~/Scripts/js/ajax-pagination.js"></script>
	<script src="~/Scripts/js/Chart.js"></script>
	<script src="~/Scripts/js/chartjs-plugin-deferred.js"></script>
	<script src="~/Scripts/js/circle-progress.js"></script>
	<script src="~/Scripts/js/loader.js"></script>
	<script src="~/Scripts/js/run-chart.js"></script>
	<script src="~/Scripts/js/jquery.magnific-popup.js"></script>
	<script src="~/Scripts/js/jquery.gifplayer.js"></script>
	<script src="~/Scripts/js/mediaelement-and-player.js"></script>
	<script src="~/Scripts/js/mediaelement-playlist-plugin.min.js"></script>

	<script src="~/Scripts/js/base-init.js"></script>
	<script defer src="~/fonts/fontawesome-all.js"></script>

	<script src="~/Content/Bootstrap/dist/js/bootstrap.bundle.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>